name: AutoPost from Google Sheets to Telegram

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  send-post:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install openai gspread oauth2client requests

    - name: Send Telegram Post
      env:
        GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python autopost.py
